### ISSUE TITLE
Adding more real dataset

### ISSUE THREAD

**Issue by jayabrata97** [decisionforce/metadrive#122]
Hi, can you add more real datasets like NGSIM, NuScenes like Argoverse?

**Comment by QuanyiLi** [comment]
Sure, we are currently testing the data imported from Waymo and Argoverse. In the future, we may consider adding supports for NGSIM and NuScenes.

**Comment by rd-zhang** [comment]
HI, is NGSIM type datasets are supported now? Thanks!
