### ISSUE TITLE
How can I successfully run env.reset() after env.close()?

### ISSUE THREAD

**Issue by Kasumigaoka-Utaha** [decisionforce/metadrive#124]
![image](https://user-images.githubusercontent.com/45712215/145326857-073e5dae-889c-4fec-b286-99ef39687cd0.png)
It gives the following result after I directly run env.reset() after env.close()

**Comment by QuanyiLi** [comment]
Hi Utaha,

Thanks for your feedback. I will fix this problem soon.

Quanyi

**Comment by QuanyiLi** [comment]
Hi, Utaha

I already fixed this problem and merged it into the main branch. Would you mind running and testing your script with the latest main branch again?
