### ISSUE TITLE
Vehicle Models in Multi Agent Environment 

### ISSUE THREAD

**Issue by BedirhanKeskin** [decisionforce/metadrive#141]
Hello, 
I am trying to change vehicle models in the multi-agent environment example. Also, I set traffic density to zero.  I want to assign different models for each car.  However, it always comes with the default model type. 

```
env = envs[env_cls_name](
        {
            "use_render": True, # if not args.pygame_render else False,
            "manual_control": True,
            "crash_done": False,
            #"agent_policy": ManualControllableIDMPolicy, # When this is open, cars can not be controlled by env.step()
            "num_agents": total_agent_number,
            #"prefer_track_agent": "agent3",
            "show_fps": True, 
            "vehicle_config": {
                "lidar": {"num_others": 4},
                "show_lidar": False,
                #"vehicle_model": "s"
                
            },
            # physics_world_step_size (float = 0.02): the minimum time interval between two time steps of bullet physics engine.
            "target_vehicle_configs": {"agent{}".format(i): {
                    "spawn_longitude": i * 10,
                    "vehicle_model": "s",
                    "max_speed":100,
                    #"use_special_color":"red",
                    "spawn_lateral": i * 1,
                    
                }
                                           for i in range(5)}

        }
    )
```

I can change each car lat. and long. inside  target_vehicle_configs but it doesn't work for the vehicle model.  On the other hand when I uncomment "vehicle_model" under "vehicle_config", it makes changes but cars are created in the same model? 

How I can define models for multiple cars.  

Thanks!!

**Comment by QuanyiLi** [comment]
Hi, BedirhanKeskin

I already fixed this for you in #142 and tested it.

Now you can customize the agent model for each agent in ```target_vehicles_config```.  Also, you can set ```random_agent_model``` to ```True``` to randomly assign models for them.

The new PR is merged with the main branch. Just pull the new main branch and enjoy it.

Quanyi
