### ISSUE TITLE
Low FPS in latest version?

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/metadrive#159]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/22206995/158559452-7172927b-12cb-4b11-9e02-a9e5c0ea2aa0.png">

I remember a fresh installation of MetaDrive should have at least 300+ FPS when running the profile script, right?

Why current version become so slow?

Any idea? @QuanyiLi

**Comment by QuanyiLi** [comment]
Maybe we should add a unit test to ensure that nothing breaks the training fps in any new PR.
