### ISSUE TITLE
Many baselines performance drop introduced in new refactoring, not sure where is the problem

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/metadrive#161]
We detect performance drop in many baseline RL algorithms. We are checking where is the problem!

**Comment by pengzhenghao** [comment]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/22206995/159151241-9e75db84-adfb-48b2-bb46-98fe9522413c.png">

a potential bug?

**Comment by QuanyiLi** [comment]
## Update:
#### SafeMetaDrive test results:
![image](https://user-images.githubusercontent.com/24489294/160055732-c0fc3940-b466-4096-b61f-e8dd384818fa.png)
The SAC-Lag and SAC still show similar success rate on SafeMetaDrive Environment.

#### MARL results:
Commits merged in 0822-0830 undermine the performance of MARL agent. I am working on it.

**Comment by pengzhenghao** [comment]
Finally we diagnosed the reasons:

* **dynamics randomization**: After a commit in 2021-08-18, we introduce dynamics randomization for default vehicle by default. This also impacts MARL environment since we are using default vehicle for all vehicles in the MARL env.

* **bug in termination handling**: We introduce a bug in 2021-08-30, which mistakenly set all vehicles to done when the environmental episode length hits `horizon`. This is not the native logic that (1) the environment stop spawns new vehicles after environmental episode length hits `horizon` and (2) existing vehicles run until die.

The following are our ablation study on the latest MetaDrive (2022-03-28). `vehicle_model=default` means using dynamics randomization, otherwise using the original static dynamics. `disable_auto_done=True` means fixing the bugs in termination handling.

Note: So `vehicle_model: default, disable_auto_done: false` (black) is current latest MetaDrive and `vehicle_model: static_default, disable_auto_done: true` (green) should be the old implementation where the experiment result in our paper generated.

#### Intersection

<img width="542" alt="image" src="https://user-images.githubusercontent.com/22206995/160315806-379db411-fb57-4345-82d7-a7f0e8e0969d.png">

#### Parking Lot

<img width="543" alt="image" src="https://user-images.githubusercontent.com/22206995/160315778-54387317-1f4e-48d1-bb1a-66771415a7f7.png">

#### Tollgate

<img width="542" alt="image" src="https://user-images.githubusercontent.com/22206995/160315824-f72d3298-bfba-438e-8a38-4bbddbc2ce38.png">


#### Bottleneck

<img width="547" alt="image" src="https://user-images.githubusercontent.com/22206995/160315854-522f6ad4-b1a0-45c9-93d1-99538ab8e206.png">


#### Roundabout

<img width="540" alt="image" src="https://user-images.githubusercontent.com/22206995/160315893-40692e76-f17c-45c4-9486-9f15e0dae52e.png">

#### PGMA (Procedural Generated Multi-Agent environment)

<img width="541" alt="image" src="https://user-images.githubusercontent.com/22206995/160315946-f288ead0-0214-4f91-b671-2885da6e5ef1.png">

**Comment by pengzhenghao** [comment]
Followup:

I suggest to revert these two changes and make them aligned with the version reported in the environment.

Or do you have any advise (like should we keep the dynamics randomization?) after reading the curves? @QuanyiLi
