### ISSUE TITLE
The reset of IDM policy is never called?

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/metadrive#163]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/22206995/160102323-fff939e1-bcaa-4ea3-8e2e-788c7a13c246.png">

**Comment by QuanyiLi** [comment]
Every policy is created and destroyed with corresponding objects. So it is not necessary to call ```reset()``` when ```env.reset()```. But you can call it at any arbitrary step as you want to clean history information.
