### ISSUE TITLE
What is neighbours_distance ? 

### ISSUE THREAD

**Issue by BedirhanKeskin** [decisionforce/metadrive#168]
Hello, 
What is the neighbours_distance and difference with the distance definition inside Lidar? 
They are inside MULTI_AGENT_METADRIVE_DEFAULT_CONFIG
I guess the unit is in meters? 
``
![Ekran görüntüsü 2022-03-31 114715](https://user-images.githubusercontent.com/71726969/161027511-cf2fa7c3-e253-438a-b910-da57029e3af4.png)

**Comment by pengzhenghao** [comment]
Hi @BedirhanKeskin ,

`neighbours_distance` is nothing to do with Lidar and it is in fact not used at all in native MetaDrive!

It is used in other work, namely one of our [previous paper](https://decisionforce.github.io/CoPO) and it is nothing to do with Lidar. Maybe we should remove it to avoid confusion.

Thanks!

**Comment by pengzhenghao** [comment]
Oh though we should probably not discuss it here, I remember you are working on Multi-agent MetaDrive and please make sure to pull latest MetaDrive. This is because we recently identify a bug that might hurt multi-agent training. See #161 for details. Thanks!

**Comment by BedirhanKeskin** [comment]
Thank you!!
Then the distance argument parameter inside the lidar dictionary affects other_v_info data acquired from lidarObserver, doesn't it?

**Comment by BedirhanKeskin** [comment]
Thanks for the great explanation!!
