### ISSUE TITLE
Ray Initialization Error

### ISSUE THREAD

**Issue by chuanyang-Zheng** [decisionforce/metadrive#76]
When I run with, I have the following error:
**(pid=2580) ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=11888, ip=137.189.88.166)
(pid=2580) AttributeError: 'NoneType' object has no attribute 'config'**

I following the setup instruction but have the above error. The operating system is windows. How can I solve it? 
Best regards.

**Comment by pengzhenghao** [comment]
Could you provide your ray version as well as the script that I can reproduce this problem?
